# Generated by Django 5.2.4 on 2025-08-08 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Place where you want to do this habit', max_length=100, verbose_name='Place')),
                ('time', models.TimeField(help_text='Time when you want to do this habit in format HH:MM', verbose_name='Time')),
                ('activity', models.CharField(help_text='Activity you want to do', max_length=100, verbose_name='Activity')),
                ('is_enjoyable', models.BooleanField(blank=True, default=True, help_text='Is this habit enjoyable', null=True, verbose_name='Enjoyable habit')),
                ('periodicity', models.CharField(choices=[('daily', ' ежедневно'), ('weekly', ' еженедельно'), ('monthly', ' ежемесячно')], default='daily', help_text='How often you want to do this activity', max_length=20, verbose_name='Periodicity')),
                ('reward', models.CharField(blank=True, help_text='Reward for doing this activity', max_length=100, null=True, verbose_name='Reward')),
                ('time_to_complete', models.PositiveIntegerField(help_text='Time to complete this activity', verbose_name='Time to complete')),
                ('is_public', models.BooleanField(blank=True, default=True, help_text='Do you want to make this habit public', null=True, verbose_name='Public habit')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Active or not', null=True, verbose_name='Active habit')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_habit', models.ForeignKey(blank=True, help_text='Related habit, only for useful habits', null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Related habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
                'ordering': ['user'],
            },
        ),
    ]
