# Generated by Django 5.2.4 on 2025-08-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_enjoyable',
            field=models.BooleanField(help_text='Is this habit enjoyable True/False', null=True, verbose_name='Enjoyable habit'),
        ),
    ]
